spring:
  jackson:
    date-format: yyyy-MM-dd
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_sys?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    password: 307314
  data:
    redis:
      # Redis本地服务器地址，注意要开启redis服务，即那个redis-server.exe
      host: 172.24.64.223
      # Redis服务器端口,默认为6379.若有改动按改动后的来
      port: 6379
      jedis:
        pool:
          # 连接池最大连接数，若为负数则表示没有任何限制
          max-active: 8
          # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 8

server:
  servlet:
    context-path: /hotel
  port: 8000
springdoc:
  api-docs:
    path: /api-docs
#    http://localhost:8080/hotel/api-docs
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/lartimes/hotel/mapper/*.xml
#    http://localhost:8080/hotel/swagger-ui/index.html#/
rocketmq:
  name-server: 172.24.64.223:9876 # 访问地址
  producer:
    group: Hotel_Group # 必须指定group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2


